### ISSUE TITLE
add env var for optional protobuf compilation

### ISSUE THREAD

**Issue by happysalada** [jabber-tools/google-cognitive-apis#6]
Could you add an environment variable to make the protobuf compilation optional ?
I'm just thinking that for releases, there is no need to recompile the protobuf definitions.

Thanks for the library!

**Comment by adambezecny** [comment]
hi,

this should be fairly easy to add. Do you feel like tailoring the change on your own and submitting PR?

regards,

Adam

**Comment by adambezecny** [comment]
Also please notice this library wrapping MS cognitive APIs:

https://github.com/jabber-tools/cognitive-services-speech-sdk-rs#build-prerequisites

I am using here env var with similar purpose (MS_COG_SVC_SPEECH_SKIP_BINDGEN)

https://github.com/jabber-tools/cognitive-services-speech-sdk-rs/blob/main/build.rs#L86-L92

looking forward your PR, will be more than happy to review and merge.

cheers,

Adam
